version: '2'
services:
  website:
    image: 'nsunina/linode_lamp:v1.0'
    stdin_open: true
    tty: true
    ports:
      - '8090:80'
    networks:
      wireshark_subnet:
        ipv4_address: 193.21.1.4
    volumes:
      - './website:/var/www/'
      - './apache2.conf:/etc/apache2/apache2.conf'
    cap_add:
      - NET_ADMIN
    privileged: true
  wireshark:
    image: 'lscr.io/linuxserver/wireshark:arm64v8-3.4.13'
    stdin_open: true
    tty: true
    ports:
      - '3000:3000'
    networks:
      wireshark_subnet:
        ipv4_address: 193.21.1.5
    environment:
      - XPRA_PW=wireshark
    cap_add:
      - NET_ADMIN
networks:
  wireshark_subnet:
    ipam:
      config:
        - subnet: 193.21.1.1/24
